### PR TITLE
update app.js

### PR DESCRIPTION
**Pull request by bangil0**
change rka.id_standar_nfs jadi rka.id_standar_harga line 2338

### CODE REVIEW

**Comment by agusnurwanto** [comment]
Kenapa dirubah pak? kolom itu bawaan dari hasil json sipd.

**Comment by bangil0** [comment]
> Kenapa dirubah pak? kolom itu bawaan dari hasil json sipd.

id_standar_harga tidak ke insert ke tabel data_rka atau belanja belanja Pak karena salah nama field,

mohon koreksi klo salah

**Comment by bangil0** [comment]
> > Kenapa dirubah pak? kolom itu bawaan dari hasil json sipd.
> 
> id_standar_harga tidak ke insert ke tabel data_rka atau belanja belanja Pak karena salah nama field,
> 
> mohon koreksi klo salah

`{
  "id_daerah": 101,
  "tahun": 2022,
  "id_unit": 565,
  "id_skpd": 497,
  "kode_skpd": "1.02.0.00.0.00.01.0000",
  "nama_skpd": "Dinas Kesehatan",
  "id_urusan": 11,
  "kode_urusan": "1",
  "nama_urusan": "URUSAN PEMERINTAHAN WAJIB YANG BERKAITAN DENGAN PELAYANAN DASAR",
  "id_bidang_urusan": 56,
  "kode_bidang_urusan": "1.02",
  "nama_bidang_urusan": "URUSAN PEMERINTAHAN BIDANG KESEHATAN",
  "id_sub_skpd": 565,
  "kode_sub_skpd": "1.02.0.00.0.00.01.0001",
  "nama_sub_skpd": "RSUD",
  "id_program": 422,
  "kode_program": "1.02.01",
  "nama_program": "PROGRAM PENUNJANG URUSAN PEMERINTAHAN DAERAH KABUPATEN/KOTA",
  "id_giat": 1869,
  "kode_giat": "1.02.01.2.10",
  "nama_giat": "Peningkatan Pelayanan BLUD",
  "id_sub_giat": 8935,
  "kode_sub_giat": "1.02.01.2.10.01",
  "nama_sub_giat": "Pelayanan dan Penunjang Pelayanan BLUD",
  "pagu": "519943970456",
  "id_akun": 4895,
  "kode_akun": "5.1.01.01.01.0001",
  "nama_akun": "5.1.01.01.01.0001 Belanja Gaji Pokok PNS ",
  "lokus_akun_teks": "",
  "jenis_bl": "btl-gaji",
  "is_paket": null,
  "subs_bl_teks": "[#]",
  "ket_bl_teks": "[-]",
  "id_standar_harga": -2,
  "kode_standar_harga": null,
  "nama_standar_harga": {
    "nama_komponen": "Belanja Gaji Pokok PNS [Belanja Gaji dan Tunjangan]",
    "spek_komponen": ""
  },
  "satuan": null,
  "spek": "",
  "rincian": "33783511766",
  "pajak": 0,
  "volume": "1",
  "harga_satuan": "33783511766",
  "koefisien": "1 Tahun",
  "vol_1": "1",
  "sat_1": "Tahun",
  "vol_2": null,
  "sat_2": null,
  "vol_3": null,
  "sat_3": null,
  "vol_4": null,
  "sat_4": null,
  "id_rinci_sub_bl": 6200891,
  "kunci_bl_rinci": 1,
  "urusan_locked": 0,
  "bidang_urusan_locked": 0,
  "program_locked": 0,
  "giat_locked": 0,
  "sub_giat_locked": 0,
  "akun_locked": 0,
  "user_created": "Ika Novia, S.KM",
  "created_date": "13-02-2021",
  "created_time": "09:41",
  "user_updated": "Ika Novia, S.KM",
  "updated_date": "14-07-2021",
  "updated_time": "07:36",
  "set_zona": "WIB",
  "action": "",
  "totalpajak": 0,
  "user1": "Ika Novia, S.KM",
  "user2": "Ika Novia, S.KM",
  "pajakmurni": 0
}`

**Comment by agusnurwanto** [comment]
siap, sudah diperbaiki mas

**Pull request closed without merging**
